export const titles = [
  { code: "mr", name: "Mr." },
  { code: "ms", name: "Ms." },
  { code: "mx", name: "Mx." },
];

export const circles = [
  { code: "friends", name: "Friends" },
  { code: "family", name: "Family" },
  { code: "colleagues", name: "Colleagues" },
];

export const countries = [
  { code: "us", name: "United States" },
  { code: "ca", name: "Canada" },
  { code: "gb", name: "United Kingdom" },
];

export const contacts = [
  {
    firstName: "John",
    lastName: "Doe",
    nick: "john",
    age: 30,
    customer: true,
    salary: "75000.00",
    title: "mr",
    country: "us",
    circle: "friends",
    expertSkill: "Java",
    skills: ["Java", "Spring", "Hibernate"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "123 Main Street",
    city: "New York",
    altContact: "Jane Doe",
    bioContent:
      "Experienced Java developer with 10 years in enterprise applications.",
  },
  {
    firstName: "Alice",
    lastName: "Smith",
    nick: "alice",
    age: 25,
    customer: false,
    salary: "55000.00",
    title: "ms",
    country: "ca",
    circle: "family",
    expertSkill: "TypeScript",
    skills: ["TypeScript", "React", "Node.js"],
    tags: [{ id: 2, color: "blue", name: "Blue" }],
    street: "456 Oak Avenue",
    city: "Toronto",
    altContact: "Bob Smith",
    bioContent:
      "Frontend specialist focusing on React and TypeScript development.",
  },
  {
    firstName: "Bob",
    lastName: "Johnson",
    nick: "bobby",
    age: 32,
    customer: true,
    salary: "80000.00",
    title: "mr",
    country: "gb",
    circle: "colleagues",
    expertSkill: "React",
    skills: ["React", "JavaScript", "CSS"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "789 Pine Road",
    city: "London",
    altContact: "Carol Johnson",
    bioContent: "React specialist with strong frontend skills.",
  },
  {
    firstName: "Carol",
    lastName: "Brown",
    nick: "carol",
    age: 27,
    customer: false,
    salary: "65000.00",
    title: "ms",
    country: "gb",
    circle: "friends",
    expertSkill: "PostgreSQL",
    skills: ["PostgreSQL", "Database", "SQL"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "321 Elm Street",
    city: "London",
    altContact: "David Brown",
    bioContent: "Database administrator with PostgreSQL expertise.",
  },
  {
    firstName: "David",
    lastName: "Wilson",
    nick: "dave",
    age: 35,
    customer: true,
    salary: "95000.00",
    title: "mr",
    country: "ca",
    circle: "family",
    expertSkill: "Next.js",
    skills: ["Next.js", "React", "TypeScript"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "654 Maple Avenue",
    city: "Vancouver",
    altContact: "Emma Wilson",
    bioContent: "Full-stack developer specializing in Next.js applications.",
  },
  {
    firstName: "Emma",
    lastName: "Davis",
    nick: "emma",
    age: 29,
    customer: false,
    salary: "72000.00",
    title: "ms",
    country: "us",
    circle: "colleagues",
    expertSkill: "Hibernate",
    skills: ["Hibernate", "Java", "Spring"],
    tags: [{ id: 2, color: "blue", name: "Blue" }],
    street: "987 Cedar Lane",
    city: "Chicago",
    altContact: "Frank Davis",
    bioContent: "Backend developer with strong Java and Hibernate skills.",
  },
  {
    firstName: "Frank",
    lastName: "Miller",
    nick: "frank",
    age: 31,
    customer: true,
    salary: "78000.00",
    title: "mr",
    country: "gb",
    circle: "friends",
    expertSkill: "MySQL",
    skills: ["MySQL", "Database", "PHP"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "147 Birch Road",
    city: "Manchester",
    altContact: "Grace Miller",
    bioContent: "Database developer with MySQL and PHP experience.",
  },
  {
    firstName: "Grace",
    lastName: "Taylor",
    nick: "grace",
    age: 26,
    customer: false,
    salary: "63000.00",
    title: "ms",
    country: "ca",
    circle: "family",
    expertSkill: "Git",
    skills: ["Git", "Linux", "DevOps"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "258 Spruce Street",
    city: "Montreal",
    altContact: "Henry Taylor",
    bioContent: "DevOps engineer with expertise in Git and Linux systems.",
  },
  {
    firstName: "Henry",
    lastName: "Anderson",
    nick: "henry",
    age: 34,
    customer: true,
    salary: "89000.00",
    title: "mr",
    country: "us",
    circle: "colleagues",
    expertSkill: "Linux",
    skills: ["Linux", "Git", "Python"],
    tags: [{ id: 2, color: "blue", name: "Blue" }],
    street: "369 Willow Avenue",
    city: "Seattle",
    altContact: "Ivy Anderson",
    bioContent: "System administrator with strong Linux and Python skills.",
  },
  {
    firstName: "Ivy",
    lastName: "Thomas",
    nick: "ivy",
    age: 25,
    customer: false,
    salary: "59000.00",
    title: "ms",
    country: "gb",
    circle: "friends",
    expertSkill: "Python",
    skills: ["Python", "Django", "Flask"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "741 Poplar Lane",
    city: "Edinburgh",
    altContact: "Jack Thomas",
    bioContent: "Python developer with web framework experience.",
  },
  {
    firstName: "Jack",
    lastName: "Jackson",
    nick: "jack",
    age: 33,
    customer: true,
    salary: "85000.00",
    title: "mr",
    country: "ca",
    circle: "family",
    expertSkill: "Django",
    skills: ["Django", "Python", "REST"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "852 Ash Street",
    city: "Calgary",
    altContact: "Kate Jackson",
    bioContent: "Backend developer specializing in Django applications.",
  },
  {
    firstName: "Kate",
    lastName: "White",
    nick: "kate",
    age: 30,
    customer: false,
    salary: "71000.00",
    title: "ms",
    country: "us",
    circle: "colleagues",
    expertSkill: "Flask",
    skills: ["Flask", "Python", "API"],
    tags: [{ id: 2, color: "blue", name: "Blue" }],
    street: "963 Hickory Road",
    city: "Denver",
    altContact: "Leo White",
    bioContent: "API developer with Flask and Python expertise.",
  },
  {
    firstName: "Leo",
    lastName: "Martin",
    nick: "leo",
    age: 28,
    customer: true,
    salary: "67000.00",
    title: "mr",
    country: "gb",
    circle: "friends",
    expertSkill: "REST",
    skills: ["REST", "API", "Node.js"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "174 Walnut Avenue",
    city: "Bristol",
    altContact: "Mia Martin",
    bioContent: "REST API developer with Node.js experience.",
  },
  {
    firstName: "Mia",
    lastName: "Garcia",
    nick: "mia",
    age: 27,
    customer: false,
    salary: "64000.00",
    title: "ms",
    country: "ca",
    circle: "family",
    expertSkill: "Node.js",
    skills: ["Node.js", "Express", "MongoDB"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "285 Cherry Lane",
    city: "Ottawa",
    altContact: "Noah Garcia",
    bioContent: "Node.js developer with Express and MongoDB skills.",
  },
  {
    firstName: "Noah",
    lastName: "Rodriguez",
    nick: "noah",
    age: 32,
    customer: true,
    salary: "81000.00",
    title: "mr",
    country: "us",
    circle: "colleagues",
    expertSkill: "Express",
    skills: ["Express", "Node.js", "REST"],
    tags: [{ id: 2, color: "blue", name: "Blue" }],
    street: "396 Peach Street",
    city: "Austin",
    altContact: "Olivia Rodriguez",
    bioContent: "Express.js developer with REST API experience.",
  },
  {
    firstName: "Olivia",
    lastName: "Lewis",
    nick: "olivia",
    age: 26,
    customer: false,
    salary: "62000.00",
    title: "ms",
    country: "gb",
    circle: "friends",
    expertSkill: "MongoDB",
    skills: ["MongoDB", "NoSQL", "Database"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "507 Plum Street",
    city: "Birmingham",
    altContact: "Paul Lewis",
    bioContent: "NoSQL database specialist with MongoDB expertise.",
  },
  {
    firstName: "Paul",
    lastName: "Lee",
    nick: "paul",
    age: 31,
    customer: true,
    salary: "79000.00",
    title: "mr",
    country: "ca",
    circle: "family",
    expertSkill: "NoSQL",
    skills: ["NoSQL", "MongoDB", "Redis"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "618 Orange Avenue",
    city: "Winnipeg",
    altContact: "Quinn Lee",
    bioContent:
      "Database architect with NoSQL and caching solutions experience.",
  },
  {
    firstName: "Quinn",
    lastName: "Walker",
    nick: "quinn",
    age: 29,
    customer: false,
    salary: "73000.00",
    title: "mx",
    country: "us",
    circle: "colleagues",
    expertSkill: "Redis",
    skills: ["Redis", "Caching", "Performance"],
    tags: [{ id: 2, color: "blue", name: "Blue" }],
    street: "729 Grape Lane",
    city: "Portland",
    altContact: "Ryan Walker",
    bioContent:
      "Performance engineer specializing in Redis and caching strategies.",
  },
  {
    firstName: "Ryan",
    lastName: "Hall",
    nick: "ryan",
    age: 33,
    customer: true,
    salary: "86000.00",
    title: "mr",
    country: "gb",
    circle: "friends",
    expertSkill: "Performance",
    skills: ["Performance", "Optimization", "Monitoring"],
    tags: [{ id: 1, color: "red", name: "Red" }],
    street: "840 Berry Road",
    city: "Glasgow",
    altContact: "Sara Hall",
    bioContent:
      "Performance optimization specialist with monitoring expertise.",
  },
  {
    firstName: "Sara",
    lastName: "Young",
    nick: "sara",
    age: 24,
    customer: false,
    salary: "57000.00",
    title: "ms",
    country: "ca",
    circle: "family",
    expertSkill: "Monitoring",
    skills: ["Monitoring", "DevOps", "Analytics"],
    tags: [{ id: 3, color: "green", name: "Green" }],
    street: "951 Apple Street",
    city: "Halifax",
    altContact: "Tom Young",
    bioContent: "DevOps engineer with monitoring and analytics experience.",
  },
];
