// ============================================================================
// Base Types
// ============================================================================

export type ID = string | number;

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | JsonObject;

export type JsonObject = {
  [key: string]: JsonValue;
};

// Async data types; the lazy loader resolves the column value or null
export type Json = Promise<JsonObject | null>;
export type Text = Promise<string | null>;
export type Binary = Promise<Buffer | null>;

// ============================================================================
// Entity Types
// ============================================================================

export type Entity = {
  readonly id?: ID | null;
  readonly version?: number | null;
  readonly createdOn?: Date | null;
  readonly updatedOn?: Date | null;
};

export type EntityClass<T extends Entity = Entity> = new () => T;

// Type-level marker carrying a collection's `mappedBy` key; never set at runtime.
export const MAPPED_BY: unique symbol = Symbol("mappedBy");

// A to-many relation that records which field on the target maps back to the
// owning entity (the schema's `mappedBy`). Structurally still T[] — the marker
// is an optional phantom property — but it lets the create types know which
// foreign key the ORM auto-fills when targets are created nested under their
// owner. Generated by the schema generator; not meant to be written by hand.
// MappedBy stays unconstrained: a constraint would become the inference
// fallback for plain T[] in MappedByKey, branding every collection.
export type ToMany<T extends Entity, MappedBy = never> = T[] & {
  readonly [MAPPED_BY]?: MappedBy;
};

// Identity types
export type InputIdentity<T extends Entity> = {
  id: ID;
  version: number;
};

export type ResultIdentity<T extends Entity> = {
  id: NonNullable<T["id"]>;
  version: number;
};

// ============================================================================
// Utility Types
// ============================================================================

export type NotNull<T> = T extends undefined ? never : T;

export type OmitByType<T, Type> = Pick<
  T,
  { [K in keyof T]-?: T[K] extends Type ? never : K }[keyof T]
>;

export type Options<T, U> = {
  [K in keyof T]: K extends keyof U ? T[K] : never;
};

export type OrderBy = "ASC" | "DESC";
